import sqlite3
import yaml
import pandas as pd
import sys
import os
from pathlib import Path

# Add repo root to sys.path
REPO_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(REPO_ROOT))

DB_PATH = REPO_ROOT / "artifacts" / "agent.db"

def get_all_signals():
    """Fetches all signals from the latest date in agent.db."""
    if not DB_PATH.exists(): return []
    conn = sqlite3.connect(DB_PATH)
    try:
        df = pd.read_sql_query(
            "SELECT * FROM preds WHERE date = (SELECT MAX(date) FROM preds) ORDER BY y_prob DESC",
            conn
        )
        return df.to_dict('records')
    except Exception:
        return []
    finally:
        conn.close()

def get_ticker_intel(ticker):
    """Fetches signal intelligence (streak, trend) for context."""
    from src.db import Database
    db = Database()
    intel = db.get_signal_intelligence()
    return intel.get(ticker, {})

from src.agent.fundamental import run_fundamental_debate

def update_rationale_in_db(ticker, date, rationale, llm_sent=None, llm_rat=None):
    """Saves the generated rationale and Gemini data back to the predictions table."""
    conn = sqlite3.connect(DB_PATH)
    try:
        conn.execute(
            "UPDATE preds SET rationale = ?, llm_sentiment = ?, llm_rationale = ? WHERE ticker = ? AND date = ?",
            (rationale, llm_sent, llm_rat, ticker, str(date))
        )
        conn.commit()
    except Exception as e:
        print(f"Error updating rationale for {ticker}: {e}")
    finally:
        conn.close()

def run_analysis():
    """Generates the Daily Digest, rationalizes all, and debates top 3 using Gemini."""
    signals = get_all_signals()
    if not signals:
        return "[DIGEST] No high-confidence signals processed yet."

    digest = f"### 🚀 DAILY SIGNAL DIGEST — {signals[0]['date'][:10]}\n\n"
    print(f"Analyzing all {len(signals)} signals for {signals[0]['date']}...")
    
    for i, s in enumerate(signals):
        ticker = s['ticker']
        date = s['date']
        conf = s['y_prob'] * 100
        signal = "LONG ↑" if s['y_pred'] == 1 else "SHORT ↓"
        intel = get_ticker_intel(ticker)
        
        streak = intel.get('streak', 0)
        streak_str = f"🔥 {streak}d" if streak > 0 else f"❄ {abs(streak)}d"
        trend = intel.get('conf_trend', 'flat')
        trend_emoji = {'rising': '↑', 'falling': '↓', 'flat': '→'}.get(trend, '→')

        # Logic-driven technical rationale
        rationale = ""
        if conf > 65 and trend == 'rising' and abs(streak) > 3:
            rationale = "Structural momentum is peaking. High conviction on sustained trend."
        elif conf > 60 and trend == 'rising':
            rationale = "Early-stage conviction building. Momentum crossover detected."
        elif trend == 'falling':
            rationale = "Signal is above threshold but conviction is fading relative to 10-day baseline."
        else:
            rationale = "Stable technical pattern detected within standard confidence bounds."

        # Execute Fundamental AI Debate ONLY for top 3 signals to conserve API bandwidth
        llm_sent = None
        llm_rat = None
        if i < 3:
            try:
                print(f"  [GEMINI] running fundamental debate for {ticker}...")
                ai_result = run_fundamental_debate(ticker, signal, round(conf,1), rationale)
                llm_sent = ai_result.get("sentiment_score", 0.5)
                llm_rat = ai_result.get("gemini_rationale")
            except Exception as e:
                print(f"  [GEMINI ERROR] {e}")

        # Save to DB for UI access
        print(f"  Writing rationales for {ticker}...")
        update_rationale_in_db(ticker, date, rationale, llm_sent, llm_rat)

        if i < 3:
            line = (
                f"**{i+1}. {ticker} — {signal}**\n"
                f"- **Confidence**: {conf:.1f}% | **Streak**: {streak_str} | **Trend**: {trend_emoji}\n"
                f"- **Technical**: {rationale}\n"
                f"- **Gemini Consensus**: {llm_rat} (Score: {llm_sent})\n"
            )
            digest += line + "\n"

    digest += "---\n*Generated by Emerald Magnetar Autonomous Analyst (Analyst-Layer v1.0)*"
    return digest

if __name__ == "__main__":
    print(run_analysis())
